# Base Configuration for AI Trading Bot
# This file contains default settings shared across all modes

ai_prompts:
  system_prompt: |
    You are a professional cryptocurrency trading AI assistant with expertise in technical analysis, 
    risk management, and market psychology. Your primary goal is to generate profitable trading 
    recommendations while maintaining strict risk management protocols.

    Key principles:
    - Always prioritize capital preservation over aggressive gains
    - Provide clear confidence scores (0.0 to 1.0) for all recommendations
    - Include specific entry, stop-loss, and take-profit levels
    - Consider current market volatility and trend direction
    - Factor in recent news and market sentiment

    Response format should include:
    - Action: BUY/SELL/HOLD
    - Confidence: 0.0-1.0
    - Entry Price: Specific price level
    - Stop Loss: Risk management level
    - Take Profit: Target profit level
    - Reasoning: Brief technical and fundamental analysis
    - Risk Level: LOW/MEDIUM/HIGH

  market_analysis_prompt: |
    Analyze the current market conditions for {trading_pair} based on the following data:

    Current Price: ${current_price}
    24h Volume: {volume_24h}
    24h Change: {change_24h}%

    Technical Indicators:
    - RSI (14): {rsi}
    - MACD: {macd}
    - Bollinger Bands: {bb_upper}/{bb_lower}
    - Support Level: ${support_level}
    - Resistance Level: ${resistance_level}

    Recent News Headlines:
    {news_headlines}

    Portfolio Status:
    - Available Balance: ${available_balance}
    - Current Positions: {open_positions}
    - Today's P&L: {daily_pnl}%

    Provide a trading recommendation considering all factors above.

  risk_assessment_prompt: |
    Evaluate the risk profile for the following trading scenario:

    Proposed Action: {action}
    Trading Pair: {trading_pair}
    Position Size: {position_size}% of portfolio
    Leverage: {leverage}x
    Current Market Volatility: {volatility}%

    Account Status:
    - Daily Losses: {daily_losses}%
    - Consecutive Losses: {consecutive_losses}
    - Max Drawdown: {max_drawdown}%
    - Open Positions: {open_positions_count}

    Assess if this trade aligns with risk management guidelines and suggest adjustments if needed.

  confidence_threshold: 0.7
  max_response_tokens: 1000
  temperature: 0.3

trading:
  mode: "testing"
  trading_pairs:
    - "BTC/USDT"
  max_position_size: 0.1  # 10% of balance per trade
  default_leverage: 1.0
  stop_loss_percentage: 2.0
  take_profit_percentage: 4.0
  order_timeout_minutes: 30

risk_management:
  max_daily_loss_percentage: 5.0
  max_consecutive_losses: 3
  max_drawdown_percentage: 10.0
  position_timeout_hours: 24
  emergency_stop_enabled: true
  volatility_threshold: 5.0

api:
  perplexity_api_key: ""  # Set via environment variable
  perplexity_model: "sonar-pro"
  pionex_api_key: ""  # Set via environment variable
  pionex_secret_key: ""  # Set via environment variable
  pionex_base_url: "https://api.pionex.com"
  pionex_ws_url: "wss://ws.pionex.com/ws"

websocket:
  mock_url: "ws://localhost:8080/mock"
  production_url: "wss://ws.pionex.com/ws"
  public_url: "wss://ws.pionex.com/ws/Pub"
  ping_interval: 30
  reconnect_attempts: 5
  reconnect_delay: 5

logging:
  level: "INFO"
  file_enabled: true
  file_path: "logs/trading_bot.log"
  console_enabled: true
  max_file_size_mb: 10
  backup_count: 5

notifications:
  discord_webhook_url: ""  # Set via environment variable
  email_enabled: false
  email_smtp_server: ""
  email_port: 587
  email_username: ""
  email_password: ""
  email_recipients: []
