# Testing Mode Configuration
# Override settings for safe testing with paper trading

trading:
  mode: "testing"
  trading_pairs:
    - "BTC/USDT"  # Single pair for focused testing
  max_position_size: 0.05  # Conservative 5% position size
  default_leverage: 1.0    # No leverage in testing
  stop_loss_percentage: 1.5
  take_profit_percentage: 3.0
  order_timeout_minutes: 15

risk_management:
  max_daily_loss_percentage: 2.0  # Very conservative
  max_consecutive_losses: 2       # Stop after 2 losses
  max_drawdown_percentage: 5.0    # Tight drawdown control
  position_timeout_hours: 12      # Shorter position timeout
  emergency_stop_enabled: true
  volatility_threshold: 3.0       # Lower volatility threshold

ai_prompts:
  confidence_threshold: 0.8  # Higher confidence required for testing
  temperature: 0.2           # More conservative AI responses

websocket:
  # Use mock endpoints for testing
  mock_url: "ws://localhost:8080/mock"

logging:
  level: "DEBUG"  # More detailed logging for testing
  console_enabled: true

# Testing specific settings
testing:
  paper_trading: true
  initial_balance: 5000.0    # $5000 virtual balance
  mock_api_responses: true
  simulate_latency: true
  latency_ms: 100
