# Production Mode Configuration
# Optimized settings for live trading

trading:
  mode: "production"
  trading_pairs:
    - "BTC/USDT"
    - "ETH/USDT"
    - "BNB/USDT"
  max_position_size: 0.15    # Larger position size for profits
  default_leverage: 2.0      # Moderate leverage
  stop_loss_percentage: 2.5
  take_profit_percentage: 5.0
  order_timeout_minutes: 45

risk_management:
  max_daily_loss_percentage: 5.0
  max_consecutive_losses: 3
  max_drawdown_percentage: 10.0
  position_timeout_hours: 24
  emergency_stop_enabled: true
  volatility_threshold: 5.0

ai_prompts:
  confidence_threshold: 0.65  # More active trading threshold
  temperature: 0.3

websocket:
  # Use real Pionex endpoints
  production_url: "wss://ws.pionex.com/ws"
  public_url: "wss://ws.pionex.com/ws/Pub"

logging:
  level: "INFO"
  console_enabled: false  # File logging only in production

notifications:
  discord_webhook_url: ""  # Will be set via environment
  email_enabled: true

# Production specific settings
production:
  real_trading: true
  enable_notifications: true
  performance_monitoring: true
  backup_interval_hours: 6
